//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novian.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public string CustomerID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<System.DateTime> AD_Date { get; set; }
        public Nullable<int> AD_User { get; set; }
        public Nullable<System.DateTime> UD_Date { get; set; }
        public Nullable<int> UD_User { get; set; }
    }
}
