//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novian.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> AD_Date { get; set; }
        public Nullable<int> AD_User { get; set; }
        public Nullable<System.DateTime> UD_Date { get; set; }
        public Nullable<int> UD_User { get; set; }
    }
}
